# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM ghcr.io/astral-sh/uv:alpine

# Set working directory
WORKDIR /app

# Copy project files into the container
COPY . /app

# Create uv virtual environment and install dependencies
RUN uv venv && uv pip install -r pyproject.toml

# Set the entrypoint command
CMD ["uv", "run", "main.py"]
